blank_issues_enabled: false
contact_links:
  - name: Flokicoin Documentation
    url: https://docs.flokicoin.org
    about: Community documentation for Flokicoin and its ecosystem.
  - name: Discord Support
    url: http://flokicoin.org/discord
    about: Join our Discord community for real-time support and discussion.
